<?php
$z[0]=Array("channelartlist","\r\n      <dl>\r\n        <dt><strong>{dede:field name='typename'/}</strong></dt>\r\n        <dd>\r\n          <ul>\r\n            {dede:channel type='son' noself='yes'}\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </dd>\r\n      </dl>\r\n      ",81,450);
$z[0][4]['typeid']="1,1";
$z[1]=Array("channelartlist","\r\n      <dl>\r\n        <dt><strong>{dede:field name='typename'/}</strong></dt>\r\n        <dd>\r\n          <ul>\r\n            {dede:channel type='son' noself='yes'}\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </dd>\r\n      </dl>\r\n      ",497,866);
$z[1][4]['typeid']="4,4";
$z[2]=Array("channelartlist","\r\n      <dl class=\"f_Business\">\r\n        <dt><strong>{dede:field name='typename'/}</strong></dt>\r\n        <dd>\r\n          <ul>\r\n            {dede:channel type='son' noself='yes'}\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </dd>\r\n      </dl>\r\n      ",913,1301);
$z[2][4]['typeid']="8,8";
$z[3]=Array("channelartlist","\r\n      <dl>\r\n        <dt><strong>{dede:field name='typename'/}</strong></dt>\r\n        <dd>\r\n          <ul>\r\n            {dede:channel type='son' noself='yes'}\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </dd>\r\n      </dl>\r\n      ",1348,1719);
$z[3][4]['typeid']="16,16";
$z[4]=Array("channelartlist","\r\n      <dl>\r\n        <dt><strong>{dede:field name='typename'/}</strong></dt>\r\n        <dd>\r\n          <ul>\r\n            {dede:channel type='son' noself='yes'}\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </dd>\r\n      </dl>\r\n      ",1766,2137);
$z[4][4]['typeid']="19,19";

?>