<?php
$z[0]=Array("channel","\r\n            <li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n            ",570,795);
$z[0][4]['typeid']="1";
$z[0][4]['currentstyle']="<li><a href='~typelink~' class=''>~typename~</a> </li>";
$z[1]=Array("channel","\r\n            <li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n            ",1073,1298);
$z[1][4]['typeid']="4";
$z[1][4]['currentstyle']="<li><a href='~typelink~' class=''>~typename~</a> </li>";
$z[2]=Array("channel","\r\n            <li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n            ",1574,1799);
$z[2][4]['typeid']="8";
$z[2][4]['currentstyle']="<li><a href='~typelink~' class=''>~typename~</a> </li>";
$z[3]=Array("channel","\r\n            <li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n            ",2079,2305);
$z[3][4]['typeid']="18";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class=''>~typename~</a> </li>";
$z[4]=Array("channel","\r\n            <li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n            ",2579,2805);
$z[4][4]['typeid']="21";
$z[4][4]['currentstyle']="<li><a href='~typelink~' class=''>~typename~</a> </li>";

?>