<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",497,522);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",591,616);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("include","",873,908);
$z[6][4]['filename']="head.htm";
$z[7]=Array("field","",1174,1232);
$z[7][4]['name']="typeid";
$z[7][4]['function']="GetTopTypename(@me)";
$z[8]=Array("channel","\r\n            <li><span class=\"l_trigon\"></span><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n            ",1392,1688);
$z[8][4]['type']="son";
$z[8][4]['currentstyle']="<li class='on'><span class='l_trigon'></span><a href='~typelink~' class='on'>~typename~</a></li>";
$z[9]=Array("field","",1838,1867);
$z[9][4]['name']="typename";
$z[10]=Array("field","",1944,1973);
$z[10][4]['name']="position";
$z[11]=Array("field","",2058,2079);
$z[11][4]['name']="content";
$z[12]=Array("include","",2175,2212);
$z[12][4]['filename']="footer.htm";

?>