<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",497,522);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",591,616);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("include","",873,908);
$z[6][4]['filename']="head.htm";
$z[7]=Array("channel","\r\n            <li><span class=\"l_trigon\"></span><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n            ",1346,1642);
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<li class='on'><span class='l_trigon'></span><a href='~typelink~' class='on'>~typename~</a></li>";
$z[8]=Array("field","",1792,1821);
$z[8][4]['name']="typename";
$z[9]=Array("field","",1898,1927);
$z[9][4]['name']="position";
$z[10]=Array("arclist","\r\n            <li>\r\n              <div class=\"img_Mask\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"130\" height=\"165\" src=\"/skin/images/team_img_1.jpg\" /></a>\r\n                <div class=\"team_img_title\"><span><a href=\"[field:arcurl/]\"><b>[field:title/]</b></a></span></div>\r\n              </div>\r\n            </li>\r\n            ",2059,2458);
$z[10][4]['row']="15";
$z[10][4]['titlelen']="30";
$z[11]=Array("pagelist","",2898,2969);
$z[11][4]['listitem']="info,index,end,pre,next,pageno";
$z[11][4]['listsize']="4";
$z[12]=Array("include","",3060,3097);
$z[12][4]['filename']="footer.htm";

?>