<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,393);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",433,491);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",520,545);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",614,639);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("include","",896,931);
$z[7][4]['filename']="head.htm";
$z[8]=Array("channel","\r\n            <li><span class=\"l_trigon\"></span><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n            ",1383,1679);
$z[8][4]['type']="son";
$z[8][4]['currentstyle']="<li class='on'><span class='l_trigon'></span><a href='~typelink~' class='on'>~typename~</a></li>";
$z[9]=Array("field","",1843,1872);
$z[9][4]['name']="typename";
$z[10]=Array("field","",1949,1978);
$z[10][4]['name']="position";
$z[11]=Array("arclist","\r\n            <dl class=\"news_l\">\r\n              <dt>\r\n                <ul>\r\n                  <li class=\"f_l\"><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                  <li style=\"list-style-type:none; list-style:none\" class=\"f_r\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</li>\r\n                </ul>\r\n              </dt>\r\n            </dl>\r\n            ",2115,2538);
$z[11][4]['row']="9";
$z[11][4]['titlelen']="80";
$z[12]=Array("pagelist","",2854,2925);
$z[12][4]['listitem']="info,index,end,pre,next,pageno";
$z[12][4]['listsize']="4";
$z[13]=Array("include","",3036,3073);
$z[13][4]['filename']="footer.htm";

?>